# -*- coding: utf-8 -*-
"""10984번_내 학점을 구해줘

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J8TP5t7ZvWkhW5aZkETtrpzVYXAKAyvE
"""

def Solution():
  T = int(input()) # 들은 학기 수

  for t in range(T):
    N = int(input())   # 들은 과목 수 
    score = 0
    C_sum = 0

    for n in range(N):
      C,G = map(float,input().split())
      score += (C*G)
      C_sum+=C
    GPA = score/C_sum
    print(int(C_sum), '%.1f' % GPA)

Solution()